### ISSUE TITLE
`AssertionError` when converting circuit to QASM and back

### ISSUE THREAD

**Issue by CalMacCQ** [CQCL/tket#1085]
```python
from pytket.circuit import Circuit, Qubit
from pytket.qasm import circuit_to_qasm_str, circuit_from_qasm_str

circuit_with_named_qubits = (
    Circuit(3, 2).H(0).CX(0, 1).H(1).CX(1, 2).H(2)
)

fake_name_map = {
    Qubit(index=0) : Qubit(index=9, name=f"Node"),
    Qubit(index=1) : Qubit(index=1, name=f"Node"),
    Qubit(index=2) : Qubit(index=2, name=f"Node"),
}

circuit_with_named_qubits.rename_units(fake_name_map)

string = circuit_to_qasm_str(circuit_with_named_qubits)

imported_circ = circuit_from_qasm_str(string)
```

This gives an `AssertionError`.  `pytket 1.20.1`

 Pretty certain its an issue with renaming the qubits. If I remove the renaming of qubits then this example works fine.
 
 Maybe the gaps in the register indices are causing issues with qasm.

**Comment by cqc-alec** [comment]
This is because QASM register names are not allowed to begin with an uppercase letter. When we convert the circuit to QASM we retain the register name, i.e. "Node", so we actually generate invalid QASM. We should probably raise an error instead. Also we should raise a better error when the reverse conversion fails for this reason.

The following is a simpler test case:

```python
c = Circuit()
qb = Qubit("Q", 0)
c.add_qubit(qb)
c.H(qb)
qasm = circuit_to_qasm_str(c)
c1 = circuit_from_qasm_str(qasm)
```

**Comment by CalMacCQ** [comment]
I agree with giving an expicit error message for this.
