### ISSUE TITLE
Stub generation fails with pybind11-stubgen 2.4

### ISSUE THREAD

**Issue by cqc-alec** [CQCL/tket#1135]
It produces a lot of errors similar to this:

```
pybind11_stubgen - [  ERROR] In pytket._tket.circuit.Circuit.get_statevector : Can't find/import 'm'
```

**Comment by trvto** [comment]
See https://github.com/sizmailov/pybind11-stubgen/issues/190

The error comes from within pybin11's binders for `Eigen` (which we use) so I think there is little we can do directly

**Comment by sizmailov** [comment]
Original numpy annotations generated by pybind11 are not valid. Newer version of `pybind11-stubgen` correctly reports the error. 

Use one of the following CLI options to rewrite the numpy annotations
```
--numpy-array-wrap-with-annotated
--numpy-array-use-type-var
--numpy-array-remove-parameters
```

**Comment by trvto** [comment]
> Original numpy annotations generated by pybind11 are not valid. Newer version of `pybind11-stubgen` correctly reports the error.
> 
> Use one of the following CLI options to rewrite the numpy annotations
> 
> ```
> --numpy-array-wrap-with-annotated
> --numpy-array-use-type-var
> --numpy-array-remove-parameters
> ```

Thanks for the tip! I've tried these options and am seeing different behaviour than expected with our binders:
- `--numpy-array-use-type-var` looks the nicest and doesn't produce the errors but, for our bindings at least, it consistently doesn't add the `dtype` parameter. For us, from, e.g. `numpy.ndarray[numpy.float32[m, 1]]`, it adds a `TypeVar` `M` and produces  `numpy.ndarray[numpy.float32[M, Literal[1]]]`, instead of the expected `numpy.ndarray[tuple[M, Literal[1]], numpy.dtype[numpy.float32]]`.

- `--numpy-array-wrap-with-annotated` seems to produce the same or similar results as without it. But the errors don't occur, which is great. 

- `--numpy-array-remove-parameters` does what I would expect and only produces `numpy.ndarray`, but we still get the errors.

I think we should be able to use the output of `--numpy-array-use-type-var` with some tweaking to our clean-up script that was handling numpy stuff already to get good results though. If I get around to it I can try to see if this option works as expected for a minimal example to see if it's something wrong with our binding code in particular.
