### ISSUE TITLE
question when convert cirucit to dag

### ISSUE THREAD

**Issue by embersax** [CQCL/tket#1187]
when I convert a quantum circuit to dag by Graph.as_nx(), when I look at the node on dag, how do I know on each node, what qubits are involved.

**Comment by cqc-alec** [comment]
It's a bit tricky, but can be done.

The `Graph` object has a bunch of attributes relating the graph to the `Circuit`, and the relevant one is `Graph.input_names`, which is a dictionary from node IDs (of input vertices) to qubit (and also classical bit) names.

Then the edge properties of the nx graph include `unit_id`, and you can look this up in the dictionary.

For example:

```python
c = Circuit(2).H(0).CX(0, 1)
g = Graph(c)
print(g.input_names)
# {0: 'q[0]', 2: 'q[1]'}
gnx = g.as_nx()
print(gnx.nodes)
# [0, 1, 2, 3, 4, 5]
print(gnx.edges(4)) # node 4 is the Hadamard gate
# [(4, 5)]
print(gnx.edges[(4,5,0)]) # 0 specifies the port number -- 0 for a single-qubit gate -- for the CX gate you'd specify 0 or 1.
# {'src_port': None, 'tgt_port': 0, 'edge_type': 'Quantum', 'unit_id': 0}
```
Since the `unit_id` is 0 this corresponds to `q[0]`.

Sorry it's so convoluted.
