### ISSUE TITLE
Valgrind errors when tests run with gcc13 builds and valgrind 3.22.

### ISSUE THREAD

**Issue by cqc-alec** [CQCL/tket#1402]
Observed here: https://github.com/CQCL/tket/actions/runs/9130680529/job/25108149969?pr=1401

Logs attached.

[valgrind.txt](https://github.com/CQCL/tket/files/15373756/valgrind.txt)

**Comment by jake-arkinstall** [comment]
I thought I'd look into this this morning, but I am out of time. A few observations along the way, which may or may not be heading in the right direction:

- `realloc() with size 0` is a relatively [recent addition](https://bugs.kde.org/show_bug.cgi?id=436413) to valgrind - if this problem occurs because of the GCC version or because of an updated valgrind?

- A modification to the lines in question (`tket/src/Clifford/ChoiMixTableau.cpp:530-532`) was made [fairly recently](https://github.com/CQCL/tket/commit/a2f6fab8a57da8787dfae94764b7c3a8e5779024#diff-b071503074cfc4512199666342ac04e29e55ec0673bafd1ec8ced8ef167d4e2f). A git bisect around that might reveal something, but it was a large commit.

- A check for zero columns or `n_rows == 1` may avoid the issue, but [Eigen is already handling this case internally](https://gitlab.com/libeigen/eigen/-/blob/master/Eigen/src/Core/util/Memory.h#L246), unless that is a recent addition. Unfortunately the blame on that section of code is a commit resulting from a clang-format.

**Comment by cqc-alec** [comment]
Ah good point, it could be due to a more recent version of valgrind (3.22 as opposed to 3.18).
