### ISSUE TITLE
Error returning depth from circuit with only Classical ops

### ISSUE THREAD

**Issue by sjdilkes** [CQCL/tket#1673]
The following code snippet:
```
from pytket.circuit import (
    Circuit,
    MultiBitOp,
    SetBitsOp,
)
from pytket.pauli import Pauli



set_bits = SetBitsOp([True, True])
multi_bit = MultiBitOp(set_bits, 2)
eq_pred_values = [True, False, False, True]
and_values = [bool(i) for i in [0, 0, 0, 1]]

circ = Circuit(4, 4, name="test")
circ.add_gate(multi_bit, [0, 1, 2, 3])

circ.add_c_predicate(eq_pred_values, [0, 1], 2, "EQ")
circ.add_c_modifier(and_values, [1], 2)

circ.measure_all()


print(circ.depth())
```

gives:

```
[tket] [critical] Assertion '!"RAW hazard created in slicing"' (../../src/Circuit/macro_circ_info.cpp : get_next_b_frontier : 400) failed.  Aborting.
```

**Comment by cqc-alec** [comment]
This issue is not specific to classical ops, but can arise with conditional ops as well. For example, this circuit:
```python
c = Circuit(2, 2)
c.X(1, condition_bits=[0, 1], condition_value=3)
c.Y(1, condition_bits=[0], condition_value=1)
c.Measure(0, 0)
```
results in the same assertion error when `c.depth()` is called.

This is the DAG:
[Circuit.gv.pdf](https://github.com/user-attachments/files/17977342/Circuit.gv.pdf)

The problem is that both the Boolean edges originating from `c[0]`, including the one terminating in the Y operation, are in the initial `b_frontier_t`; but the Quantum wire from the X to the Y operation is not in the initial `unit_frontier_t`.

This is quite reminiscent of #1357 : in both cases the issue occurs when there are multiple paths in the DAG leading from the source to the target of a Boolean wire.
