### ISSUE TITLE
Build version for linux arm architecture

### ISSUE THREAD

**Issue by luigibertaco** [CQCL/tket#359]
Hi there,

I've been trying to build a custom version of the pytket lib for linux on the arm architecture CPU (to run on a docker/ubuntu within a Macbook with the M1 chip)

However, it seems to build correctly but fails to install with a CMake error (basically doesn't seem to find the cmake command on the image, even though it just used cmake for the build)

I am just wondering if anybody has done it so far or if there are any non-official builds for arm already available.

**Comment by CalMacCQ** [comment]
Hi,

Thanks for raising this. I've seen an issue with cmake not been found before on the M1 macs. In this case this issue was resolved by installing cmake with brew. However given that you are using a docker container I don't think this will help you.

Here is a link to our build and test workflow - you could try looking here to see if  you find anything that helps. https://github.com/CQCL/tket/blob/develop/.github/workflows/build_and_test.yml

Sorry I can't be more help here.

**Comment by luigibertaco** [comment]
Thanks for that @CalMacCQ 

I had a look into that while trying before opening the issue, however, now I learned a bit more about the Linux images for Docker running on M1 chips, they are not actually ARM images, but they are AARCH64 instead.

For instance, when using Tensorflow on the M1 Mac, there is a package `tensorflow-macos` but if I need that on the Linux container on the same Mac I have to use `tensorflow-aarch64`.

It would be great to have those builds automated here too. I am very familiar with the multi-architecture builds, otherwise, I'd propose a PR myself.

At the moment, I "solved" my problem by removing the dependencies that require `pytket` as it is not my main requiremate right now, I will have to look back into this later.
